language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - cd data && ./download.py && cd ..
  - python -m pytest

notifications:
  email:
    on_success: never
    on_failure: always

